# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'videoPlayer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1112, 663)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_videoPlayer = QtWidgets.QLabel(self.centralwidget)
        self.label_videoPlayer.setGeometry(QtCore.QRect(50, 20, 800, 450))
        self.label_videoPlayer.setFrameShape(QtWidgets.QFrame.Box)
        self.label_videoPlayer.setObjectName("label_videoPlayer")
        self.pushButton_fileSelect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_fileSelect.setGeometry(QtCore.QRect(50, 500, 101, 41))
        self.pushButton_fileSelect.setObjectName("pushButton_fileSelect")
        self.pushButton_stop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_stop.setGeometry(QtCore.QRect(480, 550, 101, 41))
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.pushButton_pause = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_pause.setGeometry(QtCore.QRect(610, 550, 101, 41))
        self.pushButton_pause.setObjectName("pushButton_pause")
        self.pushButton_play = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_play.setGeometry(QtCore.QRect(740, 550, 101, 41))
        self.pushButton_play.setObjectName("pushButton_play")
        self.label_state = QtWidgets.QLabel(self.centralwidget)
        self.label_state.setGeometry(QtCore.QRect(340, 550, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_state.setFont(font)
        self.label_state.setObjectName("label_state")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(170, 510, 571, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_progress = QtWidgets.QLabel(self.centralwidget)
        self.label_progress.setGeometry(QtCore.QRect(760, 510, 71, 21))
        self.label_progress.setObjectName("label_progress")
        self.pushButton_clearPoint = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clearPoint.setGeometry(QtCore.QRect(920, 40, 121, 41))
        self.pushButton_clearPoint.setObjectName("pushButton_clearPoint")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1112, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_videoPlayer.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_fileSelect.setText(_translate("MainWindow", "File Select"))
        self.pushButton_stop.setText(_translate("MainWindow", "Stop"))
        self.pushButton_pause.setText(_translate("MainWindow", "Pause"))
        self.pushButton_play.setText(_translate("MainWindow", "Play"))
        self.label_state.setText(_translate("MainWindow", "TextLabel"))
        self.label_progress.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_clearPoint.setText(_translate("MainWindow", "Clear Points"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
